spring.application.name=crud

spring.datasource.url = jdbc:postgresql://postgresql-gmonlep.alwaysdata.net:5432/gmonlep_primerCRUD
spring.datasource.username = GMonLep
spring.datasource.password = 15de03del2003
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
